config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :candidates do
    member do
      post :vote
    end
  end
  
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/candidate.rb
class Candidate < ApplicationRecord
    has_many:vote_logs
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
    belongs_to :user
    has_many :products
end

app/models/user.rb
class User < ApplicationRecord
    has_one :store
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate,counter_cache:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
    before_action :find_candidate, only: [:edit, :update, :destroy, :vote]
    
    def index
        @candidates = Candidate.all
    end

    def new
        @candidate = Candidate.new
        
    end

    def create
        @candidate = Candidate.new(candidate_params)
        
        if @candidate.save
            #成功
            ContactMailer.say_hello_to(@candidate).deliver_now
            redirect_to candidates_path, notice: "新增候选人成功！"
        else
            #失败
            render :new
        end
    end

    def edit
        #@candidate = Candidate.find_by(id:params[:id])
    end

    def update
        #@candidate = Candidate.find_by(id:params[:id])

        if @candidate.update(candidate_params)
            #成功
            redirect_to candidates_path, notice: "资料更新成功！"
        else
            #失败
            render :edit
        end 
        
    end

    def destroy
        #@candidate = Candidate.find_by(id:params[:id])
        @candidate.destroy if @candidate
        redirect_to candidates_path, notice: "资料删除成功！"
        
        
    end

    def vote
        #@candidate = Candidate.find_by(id:params[:id])
        @candidate.vote_logs.create(ip_address:request.remote_ip) if @candidate
        redirect_to candidates_path, notice: "完成投票！"
    end 

    private
    
    def candidate_params
        params.require(:candidate).permit(:name,:age,:party,:politics)

    end
    
    def find_candidate
        @candidate = Candidate.find_by(id:params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def icon_link_to(label, path, icon)
      link_to path do
        content_tag :span, class: "glyphicon glyphicon-#{icon}" do
          label
        end
      end
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
  <%= simple_form_for(candidate) do |f| %>
    <%= f.input :name, label: "姓名" %>
    <%= f.input :age, label: "年齡" %>
    <%= f.input :party, label: "政黨" %>
    <%= f.input :politics, label: "政見" %>
    <%= f.submit %>
  <% end %>

app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>

  <%= render "form", candidate: @candidate %>

  <br />
  
  <%= link_to '回候選人列表', candidates_path %>

app/views/candidates/index.html.erb
<h1>候選人列表</h1>

<%= icon_link_to "新增候選人", new_candidate_path, "knight" %>

    <table class="table">
        <thead>
            <tr>
                <td>投票</td>
                <td>候選人姓名</td>
                <td>政黨</td>
                <td>政見</td>
                <td>得票數</td>
                <td>操作</td>
            </tr>
        </thead>

        <body>
            <% @candidates.each do |candidate| %>
                <tr>
                    <td>
                        <%= link_to "投給這位", vote_candidate_path(candidate), method: "post", data: { confirm: "確定投給這個人?"},class:"btn btn-danger btn-xs" %>
                    </td>
                    <td>
                        <%= candidate.name %>(年齡：
                            <%= candidate.age %> 歲)</td>
                    <td>
                        <%= candidate.party %>
                    </td>
                    <td>
                        <%= candidate.politics %>
                    </td>
                    <td>
                        <%= candidate.vote_logs.size %>
                    </td>
                    <td>
                        <%= link_to "編輯", edit_candidate_path(candidate) %>
                            <%= link_to "刪除", candidate_path(candidate), method: "delete", data: { confirm: "確認刪除" } %>
                    </td>
                </tr>
                <% end %>
        </body>
    </table>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

  <%= render "form", candidate: @candidate %>

 <br />

 <%= link_to '回候選人列表', candidates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCandidates</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice%>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>